version: "3"

services:
  proxy:
    image: nginx:1.15-alpine
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - biblioteca-pessoal

  biblioteca-pessoal:
    build:
      dockerfile: dockerFile
      context: .
    # env_file: .env
    volumes:
      - ".:/www"
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    env_file: .env
    # volumes:
    #   - ./database:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

networks:
  default:
    external:
      name: gces-network 